### ISSUE TITLE
AsRawFd and FromRawFd trait support?

### ISSUE THREAD

**Issue by xhebox** [de-vri-es/tokio-seqpacket-rs#4]
I want to use the package to play around with wayland. One of the cases is that: the parent process has opened the socket fd for you, and you may want to open the socket by fd directly.

**Comment by de-vri-es** [comment]
Good point!

We can't really implement `FromRawFd`, because registration with the tokio runtime can fail. That's also why none of the tokio sockets implement it themselves.

However, I did add a `from_raw_fd() -> std::io::Result<Self>` function to the socket struct along with `as/into_raw_fd()` and the `As/IntoRawFd` traits.

Released with 0.4.3.

Thanks for brining this up!
